### ISSUE TITLE
Request: `pyproject.toml`-based configuration

### ISSUE THREAD

**Issue by jamesbraza** [srstevenson/nb-clean#259]
I currently use `nb-clean` in my `pre-commit` config like so:

```yaml
---
default_language_version:
    python: python3

repos:
    - repo: https://github.com/srstevenson/nb-clean
      rev: 3.2.0
      hooks:
          - id: nb-clean
            args: [--preserve-cell-outputs, --remove-empty-cells]
```

It would be nice if the `args` could be moved to a `pyproject.toml`, so that running `nb-clean clean` locally (outside of `pre-commit`) could also use the same configuration.
